/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package eu.ideata.streaming.core;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class UserInfo extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8795558432313671980L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"UserInfo\",\"namespace\":\"eu.ideata.streaming.core\",\"fields\":[{\"name\":\"userId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"timestamp\",\"type\":\"long\"},{\"name\":\"booleanFlag\",\"type\":\"boolean\"},{\"name\":\"subCategory\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"someValue\",\"type\":\"float\"},{\"name\":\"intValue\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.String userId;
  @Deprecated public long timestamp;
  @Deprecated public boolean booleanFlag;
  @Deprecated public java.lang.String subCategory;
  @Deprecated public float someValue;
  @Deprecated public int intValue;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public UserInfo() {}

  /**
   * All-args constructor.
   * @param userId The new value for userId
   * @param timestamp The new value for timestamp
   * @param booleanFlag The new value for booleanFlag
   * @param subCategory The new value for subCategory
   * @param someValue The new value for someValue
   * @param intValue The new value for intValue
   */
  public UserInfo(java.lang.String userId, java.lang.Long timestamp, java.lang.Boolean booleanFlag, java.lang.String subCategory, java.lang.Float someValue, java.lang.Integer intValue) {
    this.userId = userId;
    this.timestamp = timestamp;
    this.booleanFlag = booleanFlag;
    this.subCategory = subCategory;
    this.someValue = someValue;
    this.intValue = intValue;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return userId;
    case 1: return timestamp;
    case 2: return booleanFlag;
    case 3: return subCategory;
    case 4: return someValue;
    case 5: return intValue;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: userId = (java.lang.String)value$; break;
    case 1: timestamp = (java.lang.Long)value$; break;
    case 2: booleanFlag = (java.lang.Boolean)value$; break;
    case 3: subCategory = (java.lang.String)value$; break;
    case 4: someValue = (java.lang.Float)value$; break;
    case 5: intValue = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'userId' field.
   * @return The value of the 'userId' field.
   */
  public java.lang.String getUserId() {
    return userId;
  }

  /**
   * Sets the value of the 'userId' field.
   * @param value the value to set.
   */
  public void setUserId(java.lang.String value) {
    this.userId = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return The value of the 'timestamp' field.
   */
  public java.lang.Long getTimestamp() {
    return timestamp;
  }

  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(java.lang.Long value) {
    this.timestamp = value;
  }

  /**
   * Gets the value of the 'booleanFlag' field.
   * @return The value of the 'booleanFlag' field.
   */
  public java.lang.Boolean getBooleanFlag() {
    return booleanFlag;
  }

  /**
   * Sets the value of the 'booleanFlag' field.
   * @param value the value to set.
   */
  public void setBooleanFlag(java.lang.Boolean value) {
    this.booleanFlag = value;
  }

  /**
   * Gets the value of the 'subCategory' field.
   * @return The value of the 'subCategory' field.
   */
  public java.lang.String getSubCategory() {
    return subCategory;
  }

  /**
   * Sets the value of the 'subCategory' field.
   * @param value the value to set.
   */
  public void setSubCategory(java.lang.String value) {
    this.subCategory = value;
  }

  /**
   * Gets the value of the 'someValue' field.
   * @return The value of the 'someValue' field.
   */
  public java.lang.Float getSomeValue() {
    return someValue;
  }

  /**
   * Sets the value of the 'someValue' field.
   * @param value the value to set.
   */
  public void setSomeValue(java.lang.Float value) {
    this.someValue = value;
  }

  /**
   * Gets the value of the 'intValue' field.
   * @return The value of the 'intValue' field.
   */
  public java.lang.Integer getIntValue() {
    return intValue;
  }

  /**
   * Sets the value of the 'intValue' field.
   * @param value the value to set.
   */
  public void setIntValue(java.lang.Integer value) {
    this.intValue = value;
  }

  /**
   * Creates a new UserInfo RecordBuilder.
   * @return A new UserInfo RecordBuilder
   */
  public static eu.ideata.streaming.core.UserInfo.Builder newBuilder() {
    return new eu.ideata.streaming.core.UserInfo.Builder();
  }

  /**
   * Creates a new UserInfo RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new UserInfo RecordBuilder
   */
  public static eu.ideata.streaming.core.UserInfo.Builder newBuilder(eu.ideata.streaming.core.UserInfo.Builder other) {
    return new eu.ideata.streaming.core.UserInfo.Builder(other);
  }

  /**
   * Creates a new UserInfo RecordBuilder by copying an existing UserInfo instance.
   * @param other The existing instance to copy.
   * @return A new UserInfo RecordBuilder
   */
  public static eu.ideata.streaming.core.UserInfo.Builder newBuilder(eu.ideata.streaming.core.UserInfo other) {
    return new eu.ideata.streaming.core.UserInfo.Builder(other);
  }

  /**
   * RecordBuilder for UserInfo instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<UserInfo>
    implements org.apache.avro.data.RecordBuilder<UserInfo> {

    private java.lang.String userId;
    private long timestamp;
    private boolean booleanFlag;
    private java.lang.String subCategory;
    private float someValue;
    private int intValue;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(eu.ideata.streaming.core.UserInfo.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.userId)) {
        this.userId = data().deepCopy(fields()[0].schema(), other.userId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[1].schema(), other.timestamp);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.booleanFlag)) {
        this.booleanFlag = data().deepCopy(fields()[2].schema(), other.booleanFlag);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.subCategory)) {
        this.subCategory = data().deepCopy(fields()[3].schema(), other.subCategory);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.someValue)) {
        this.someValue = data().deepCopy(fields()[4].schema(), other.someValue);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.intValue)) {
        this.intValue = data().deepCopy(fields()[5].schema(), other.intValue);
        fieldSetFlags()[5] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing UserInfo instance
     * @param other The existing instance to copy.
     */
    private Builder(eu.ideata.streaming.core.UserInfo other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.userId)) {
        this.userId = data().deepCopy(fields()[0].schema(), other.userId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[1].schema(), other.timestamp);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.booleanFlag)) {
        this.booleanFlag = data().deepCopy(fields()[2].schema(), other.booleanFlag);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.subCategory)) {
        this.subCategory = data().deepCopy(fields()[3].schema(), other.subCategory);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.someValue)) {
        this.someValue = data().deepCopy(fields()[4].schema(), other.someValue);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.intValue)) {
        this.intValue = data().deepCopy(fields()[5].schema(), other.intValue);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'userId' field.
      * @return The value.
      */
    public java.lang.String getUserId() {
      return userId;
    }

    /**
      * Sets the value of the 'userId' field.
      * @param value The value of 'userId'.
      * @return This builder.
      */
    public eu.ideata.streaming.core.UserInfo.Builder setUserId(java.lang.String value) {
      validate(fields()[0], value);
      this.userId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'userId' field has been set.
      * @return True if the 'userId' field has been set, false otherwise.
      */
    public boolean hasUserId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'userId' field.
      * @return This builder.
      */
    public eu.ideata.streaming.core.UserInfo.Builder clearUserId() {
      userId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * @return The value.
      */
    public java.lang.Long getTimestamp() {
      return timestamp;
    }

    /**
      * Sets the value of the 'timestamp' field.
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public eu.ideata.streaming.core.UserInfo.Builder setTimestamp(long value) {
      validate(fields()[1], value);
      this.timestamp = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * @return This builder.
      */
    public eu.ideata.streaming.core.UserInfo.Builder clearTimestamp() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'booleanFlag' field.
      * @return The value.
      */
    public java.lang.Boolean getBooleanFlag() {
      return booleanFlag;
    }

    /**
      * Sets the value of the 'booleanFlag' field.
      * @param value The value of 'booleanFlag'.
      * @return This builder.
      */
    public eu.ideata.streaming.core.UserInfo.Builder setBooleanFlag(boolean value) {
      validate(fields()[2], value);
      this.booleanFlag = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'booleanFlag' field has been set.
      * @return True if the 'booleanFlag' field has been set, false otherwise.
      */
    public boolean hasBooleanFlag() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'booleanFlag' field.
      * @return This builder.
      */
    public eu.ideata.streaming.core.UserInfo.Builder clearBooleanFlag() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'subCategory' field.
      * @return The value.
      */
    public java.lang.String getSubCategory() {
      return subCategory;
    }

    /**
      * Sets the value of the 'subCategory' field.
      * @param value The value of 'subCategory'.
      * @return This builder.
      */
    public eu.ideata.streaming.core.UserInfo.Builder setSubCategory(java.lang.String value) {
      validate(fields()[3], value);
      this.subCategory = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'subCategory' field has been set.
      * @return True if the 'subCategory' field has been set, false otherwise.
      */
    public boolean hasSubCategory() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'subCategory' field.
      * @return This builder.
      */
    public eu.ideata.streaming.core.UserInfo.Builder clearSubCategory() {
      subCategory = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'someValue' field.
      * @return The value.
      */
    public java.lang.Float getSomeValue() {
      return someValue;
    }

    /**
      * Sets the value of the 'someValue' field.
      * @param value The value of 'someValue'.
      * @return This builder.
      */
    public eu.ideata.streaming.core.UserInfo.Builder setSomeValue(float value) {
      validate(fields()[4], value);
      this.someValue = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'someValue' field has been set.
      * @return True if the 'someValue' field has been set, false otherwise.
      */
    public boolean hasSomeValue() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'someValue' field.
      * @return This builder.
      */
    public eu.ideata.streaming.core.UserInfo.Builder clearSomeValue() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'intValue' field.
      * @return The value.
      */
    public java.lang.Integer getIntValue() {
      return intValue;
    }

    /**
      * Sets the value of the 'intValue' field.
      * @param value The value of 'intValue'.
      * @return This builder.
      */
    public eu.ideata.streaming.core.UserInfo.Builder setIntValue(int value) {
      validate(fields()[5], value);
      this.intValue = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'intValue' field has been set.
      * @return True if the 'intValue' field has been set, false otherwise.
      */
    public boolean hasIntValue() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'intValue' field.
      * @return This builder.
      */
    public eu.ideata.streaming.core.UserInfo.Builder clearIntValue() {
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    public UserInfo build() {
      try {
        UserInfo record = new UserInfo();
        record.userId = fieldSetFlags()[0] ? this.userId : (java.lang.String) defaultValue(fields()[0]);
        record.timestamp = fieldSetFlags()[1] ? this.timestamp : (java.lang.Long) defaultValue(fields()[1]);
        record.booleanFlag = fieldSetFlags()[2] ? this.booleanFlag : (java.lang.Boolean) defaultValue(fields()[2]);
        record.subCategory = fieldSetFlags()[3] ? this.subCategory : (java.lang.String) defaultValue(fields()[3]);
        record.someValue = fieldSetFlags()[4] ? this.someValue : (java.lang.Float) defaultValue(fields()[4]);
        record.intValue = fieldSetFlags()[5] ? this.intValue : (java.lang.Integer) defaultValue(fields()[5]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
